DROP TABLE IF EXISTS "APK Information";
CREATE TABLE "APK Information" ("Name" TEXT, "Version" FLOAT, "ID" INTEGER PRIMARY KEY  NOT NULL , "Developer" TEXT);
DROP TABLE IF EXISTS "Privilage";
CREATE TABLE "Privilage" ("APK-Id" INTEGER, "Id" INTEGER PRIMARY KEY  NOT NULL );
